#jinja2: trim_blocks: True, lstrip_blocks: True
defaultRules:
  rules:
     alertManager: true
alertmanager:
  enabled: true
  {% if CEPH_STORAGE_CLASS is defined %}
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: {{ CEPH_STORAGE_CLASS }}
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
  {% endif %}
  config:
    {% if smtp_host is defined %}
    global:
      smtp_smarthost: '{{ smtp_host }}'
      smtp_from: '{{ smtp_from }}'
      smtp_auth_username: "{{ smtp_user }}"
      smtp_auth_password: "{{ smtp_pass }}"
      smtp_require_tls: true
    {% endif %}
  {% if alert_email_receiver is defined %}
    route:
      group_by: ['alertname', 'prometheus', 'namespace']
      receiver: 'null'
      routes:
      - receiver: 'null'
        match:
          alertname: Watchdog
      - receiver: 'email'
        match:
          severity: critical
    receivers:
      - name: 'null'
      - name: 'email'
        email_configs:
        - to: '{{ alert_email_receiver }}'
  {% endif %}
grafana:
  adminPassword: "{{ grafana_password }}"
  {% if CEPH_STORAGE_CLASS is defined %}
  persistence:
    enabled: true
    type: pvc
    storageClassName: {{ CEPH_STORAGE_CLASS }}
    size: 4Gi
    accessModes:
    - ReadWriteOnce
    finalizers:
    - kubernetes.io/pvc-protection
  {% endif %}
  grafana.ini:
    smtp:
      enabled: true
      host: "{{ smtp_host }}"
      user: "{{ smtp_user }}"
      password: "{{ smtp_pass }}"
      from_address: "{{ smtp_from }}"
  smtp:
    existingSecret: ""
    userKey: "user"
    passwordKey: "password"
    
{% if CEPH_STORAGE_CLASS is defined %}
thanosRuler:
  thanosRulerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: {{ CEPH_STORAGE_CLASS }}
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi
{% endif %}

prometheus:
  prometheusSpec:
    {% if CEPH_STORAGE_CLASS is defined %}
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: {{ CEPH_STORAGE_CLASS }}
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    {% endif %}